title = "Calendario Cientifico"
baseURL = "https://calendario-cientifico-escolar.github.io/"
languageCode = "es-ES"
theme = "ananke"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.es]
    title = "Calendario Cientifico"
    weight = 1
    contentDir = "content/es"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Un aniversario científico para cada día del año."
  facebook = ""
  twitter = "https://twitter.com/CalCientifico"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "black bg-light-silver"
  text_color_class = "red"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

[menu]

  [[menu.main]]
    identifier = "enlaces"
    name = "Links"
    pre = ""
    url = "/enlaces/"
    weight = -110
    [menu.main.params]
      class = "highlight-menu-item"

  [[menu.main]]
    identifier = "telegram"
    name = "Telegram"
    pre = ""
    url = "/telegram/"
    weight = -120
    [menu.main.params]
      class = "highlight-menu-item-kk"
            
  [[menu.main]]
    identifier = "iCal"
    name = "iCal"
    pre = ""
    url = "/ical/"
    weight = -130
    [menu.main.params]
      class = "highlight-menu-item-kk"
                  