name: groovy-github-actions
on: [push]
jobs:
  check-groovy:
    runs-on: groovy:3.0-jre11
    steps:
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
         candidate: groovy
         version: 3.0.5
      - run: groovy scripts/telegram.groovy
