name: groovy-github-actions
on: [push]
jobs:
  check-groovy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: install
        shell: bash
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 3.0.5
          groovy scripts/telegram.groovy
