name: twitter
on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Year'     
        required: true
        default: '2021'
      month:
        description: 'Month'
        required: true
      day:
        description: 'Day'
        required: true
      lang:
        description: 'Lang'
        required: true
        default: 'es'
jobs:
  check-groovy:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_KEY: ${{ secrets.CONSUMERKEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.CONSUMERSECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.ACCESSTOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESSTOKENSECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: manual
        if: github.event.inputs.lang
        run: |          
          npm install
          node scripts/twitter.js ${{ github.event.inputs.lang }} ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} 

      - name: esp
        if: github.event.schedule=='0 4 * * *'
        run: |          
          npm install
          node scripts/twitter.js es ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} 

      - name: gal
        if: github.event.schedule=='5 4 * * *'
        run: |          
          npm install
          node scripts/twitter.js gal ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} 

      - name: astu
        if: github.event.schedule=='10 4 * * *'
        run: |          
          npm install
          node scripts/twitter.js astu ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} 

      - name: eus
        if: github.event.schedule=='15 4 * * *'
        run: |          
          npm install
          node scripts/twitter.js eus ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} 

      - name: cat
        if: github.event.schedule=='20 4 * * *'
        run: |          
          npm install
          node scripts/twitter.js cat ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} 

      - name: arag
        if: github.event.schedule=='25 4 * * *'
        run: |          
          npm install
          node scripts/twitter.js arag ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} 

      - name: en
        if: github.event.schedule=='30 4 * * *'
        run: |          
          npm install
          node scripts/twitter.js en ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} 
